import type { SummStatFilterState } from "@/types/filter-state";

export const INITIAL_SUMM_FILTERS: SummStatFilterState = {
  phases: [],
  var_1: "",
  data_1: [],
  reg_1: [],
  mpp_1: 0.5,
  chrms_1: [],
  ancs_1: [],
  var_2_1: "",
  var_2_2: "",
  col: [],
  fac_x: [],
  fac_y: [],
  mea_med_1: false,
  mea_med_x: false,
  mea_med_y: false,
  plot: "",
  n_bins: 20,
  x_axis: "Free Axis",
  min_x_axis: 0,
  max_x_axis: 0,
  y_axis: "Free Axis",
  min_y_axis: 0,
  max_y_axis: 0,
  map_data: true,
  map_data_rad: 15,
  map_reg: true,
  map_reg_rad: 10,
  map_pop: true,
  map_pop_rad: 15,
  map_ind_rad: 3,
  map_lat_jit: 1,
  map_lon_jit: 1,
  tree_lin: [],
  bandwidth_divisor: 30,
  thresholds: 10,
};

export const DEFAULTS_BY_PLOT: Record<
  Exclude<SummStatFilterState["plot"], "">,
  Partial<SummStatFilterState>
> = {
  Violin: {
    var_1: "Mean Length (bp)",
    phases: ["Unphased"],
    reg_1: ["East Asia", "Europe", "South Asia", "Oceania", "Central Asia"],
    mpp_1: 0.5,
    chrms_1: ["Autosome"],
    ancs_1: ["All"],
    col: ["Region"],
    fac_x: ["Dataset"],
    fac_y: [],
    mea_med_1: true,
    x_axis: "Shared Axis",
    min_x_axis: 0,
    max_x_axis: 0,
    y_axis: "Shared Axis",
    min_y_axis: 0,
    max_y_axis: 0,
    tree_lin: [],
    bandwidth_divisor: 30,
  },
  Density: {
    var_1: "Mean Length (bp)",
    phases: ["Phased", "Unphased"],
    reg_1: ["East Asia", "Europe", "South Asia", "Oceania", "Central Asia"],
    mpp_1: 0.5,
    chrms_1: ["Autosome"],
    ancs_1: ["All"],
    col: ["Region"],
    fac_x: [],
    fac_y: ["Phase state"],
    mea_med_1: true,
    x_axis: "Shared Axis",
    min_x_axis: 0,
    max_x_axis: 0,
    y_axis: "Free Axis",
    min_y_axis: 0,
    max_y_axis: 0,
    tree_lin: [],
    bandwidth_divisor: 10,
  },
  Histogram: {
    var_1: "Mean Length (bp)",
    phases: ["Unphased", "Phased"],
    reg_1: ["East Asia", "Europe", "South Asia", "Oceania", "Central Asia"],
    mpp_1: 0.5,
    chrms_1: ["Autosome"],
    ancs_1: ["All"],
    col: ["Region"],
    fac_x: ["Phase state"],
    fac_y: ["Dataset"],
    mea_med_1: true,
    n_bins: 50,
    x_axis: "Shared Axis",
    min_x_axis: 0,
    max_x_axis: 0,
    y_axis: "Free Axis",
    min_y_axis: 0,
    max_y_axis: 0,
    tree_lin: [],
  },
  Map: {
    map_data: true,
    phases: ["Unphased", "Phased"],
    reg_1: ["East Asia", "Europe", "South Asia", "Oceania", "Central Asia"],
    mpp_1: 0.5,
    chrms_1: ["Autosome"],
    ancs_1: ["All"],
    var_1: "Mean Length (bp)",
    map_data_rad: 50,
    map_reg: true,
    map_reg_rad: 15,
    map_pop: false,
    map_pop_rad: 10,
    map_ind_rad: 3,
    map_lat_jit: 1,
    map_lon_jit: 1,
  },
  Points: {
    var_2_1: "Mean Length (bp)",
    var_2_2: "Max Length (bp)",
    data_1: ["Diploid", "Phased"],
    phases: ["Unphased", "Phased"],
    reg_1: ["East Asia", "Europe", "South Asia", "Oceania", "Central Asia"],
    mpp_1: 0.5,
    chrms_1: ["Autosome"],
    ancs_1: ["All"],
    col: ["Region"],
    fac_x: ["Dataset"],
    fac_y: [],
    mea_med_x: false,
    mea_med_y: false,
    x_axis: "Shared Axis",
    min_x_axis: 0,
    max_x_axis: 0,
    y_axis: "Shared Axis",
    min_y_axis: 0,
    max_y_axis: 0,
    tree_lin: ["HGDP00535_HGDP", "HGDP00535_PGNO", "HG02351_1KGP"],
  },
  "2D Density": {
    var_2_1: "Mean Length (bp)",
    var_2_2: "Max Length (bp)",
    phases: ["Unphased", "Phased"],
    reg_1: ["East Asia", "Europe", "South Asia", "Oceania", "Central Asia"],
    mpp_1: 0.5,
    chrms_1: ["Autosome"],
    ancs_1: ["All"],
    col: [],
    fac_x: [],
    fac_y: [],
    mea_med_x: false,
    mea_med_y: false,
    x_axis: "Shared Axis",
    min_x_axis: 0,
    max_x_axis: 0,
    y_axis: "Shared Axis",
    min_y_axis: 0,
    max_y_axis: 0,
    tree_lin: [],
    bandwidth_divisor: 10,
    thresholds: 10,
  },
};
