import { SUMM_STAT_FRAG_AXIS_MODES } from "@/pages/sum_stats_frag/config/options";
import { mapping } from "@/pages/sum_stats_frag/static/mapping";

export const mppMarks = [
  { value: 50, label: "50%" },
  { value: 55, label: "" },
  { value: 60, label: "" },
  { value: 65, label: "65%" },
  { value: 70, label: "" },
  { value: 75, label: "" },
  { value: 80, label: "80%" },
  { value: 85, label: "" },
  { value: 90, label: "" },
  { value: 95, label: "95%" },
];

export const optionsAxis = [...SUMM_STAT_FRAG_AXIS_MODES];

export const binMarks = [
  { value: 0, label: "0" },
  { value: 25, label: "25" },
  { value: 50, label: "50" },
  { value: 75, label: "75" },
  { value: 100, label: "100" },
];

export const bandwidthDivisorMarks = [
  { value: 1, label: "Dense" },
  { value: 100, label: "Light" },
];

export const tdBandwidthDivisorMarks = [
  { value: 1, label: "Detailed" },
  { value: 50, label: "Smooth" },
];

export const tdThresholdDivisorMarks = [
  { value: 10, label: "Less" },
  { value: 45, label: "More" },
];

export const ancestries = {
  options: [
    "Vindija",
    "Chagyrskaya",
    "Altai",
    "Denisova",
    "Ambiguous",
    "AmbigNean",
    "nonDAVC",
    "Neanderthal",
  ],
};

export const chromosomes = {
  options: [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "X",
  ],
};

export const variables = {
  allOptions: [
    "Chromosome",
    "Start",
    "End",
    "Length",
    "Haplotype",
    "Mean Post. Prob.",
    "Called Seq.",
    "Mutation Rate",
    "SNPs",
    "Admixt. Pop. Variants",
    "Link. DAVC",
    "Vindija",
    "Chagyrskaya",
    "Altai",
    "Denisova",
    "Private Vindija",
    "Private Chagyrskaya",
    "Private Altai",
    "Private Denisova",
    "Shared Neanderthal",
    "Shared Archaic",
    "Ancestry",
    "Min. Distance Ancestry",
    "Min. Distance Value",
    "Ancestry Z test",
    "Distance Z test",
    "P-val Z test",
    "Individual",
    "Phase State",
    "Individual Phase",
    "Sex",
    "Population",
    "Region",
    "Dataset",
  ],
  discreteOptions: [
    "Chromosome",
    "Haplotype",
    "Ancestry",
    "Min. Distance Ancestry",
    "Ancestry Z test",
    "Individual",
    "Phase State",
    "Individual Phase",
    "Sex",
    "Population",
    "Region",
    "Dataset",
  ],
  continousOptions: [
    "Start",
    "End",
    "Length",
    "Mean Post. Prob.",
    "Called Seq.",
    "Mutation Rate",
    "SNPs",
    "Admixt. Pop. Variants",
    "Link. DAVC",
    "Vindija",
    "Chagyrskaya",
    "Altai",
    "Denisova",
    "Private Vindija",
    "Private Chagyrskaya",
    "Private Altai",
    "Private Denisova",
    "Shared Neanderthal",
    "Shared Archaic",
    "Min. Distance Value",
    "Distance Z test",
    "P-val Z test",
  ],
  continuousOptions: [
    "Start",
    "End",
    "Length",
    "Mean Post. Prob.",
    "Called Seq.",
    "Mutation Rate",
    "SNPs",
    "Admixt. Pop. Variants",
    "Link. DAVC",
    "Vindija",
    "Chagyrskaya",
    "Altai",
    "Denisova",
    "Private Vindija",
    "Private Chagyrskaya",
    "Private Altai",
    "Private Denisova",
    "Shared Neanderthal",
    "Shared Archaic",
    "Min. Distance Value",
    "Distance Z test",
    "P-val Z test",
  ],
};

export const mappingToLong = {
  ...mapping.toLong,
  ...mapping.values.anc.toLong,
  ...mapping.values.reg.toLong,
  ...mapping.values.phase_state.toLong,
  ...mapping.values.sex.toLong,
  F: "Female",
  M: "Male",
  EUR: "Europe",
  MID: "Middle East",
  SAS: "South Asia",
  AFR: "Africa",
  EAS: "East Asia",
  AMR: "America",
  OCE: "Oceania",
  CAS: "Central Asia",
  unphased: "Unphased",
  phased: "Phased",
  nonDAVC: "nonDAVC",
};
