import type { SummStatFragFilterState } from "@/types/filter-state";

export const DEFAULT_FRAGMENT_INDIVIDUALS = [
  "HGDP00535_unphased",
  "HGDP00536_unphased",
  "HGDP01149_unphased",
];

export const DEFAULT_FRAGMENT_ANCESTRIES = [
  "Vindija",
  "Chagyrskaya",
  "Altai",
  "Denisova",
  "Ambiguous",
  "AmbigNean",
  "nonDAVC",
  "Neanderthal",
];

export const DEFAULT_FRAGMENT_CHROMOSOMES = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "X",
];

export const INITIAL_SUMM_FRAG_FILTERS: SummStatFragFilterState = {
  tree_lin: DEFAULT_FRAGMENT_INDIVIDUALS,
  mpp: 50,
  ancs: DEFAULT_FRAGMENT_ANCESTRIES,
  chrms: DEFAULT_FRAGMENT_CHROMOSOMES,
  var_1: "Length",
  var_2_1: "Length",
  var_2_2: "Mean Post. Prob.",
  col: ["Ancestry"],
  fac_x: ["Dataset"],
  fac_y: [],
  mea_med_1: false,
  mea_med_x: false,
  mea_med_y: false,
  plot: "Histogram",
  n_bins: 50,
  x_axis: "Free Axis",
  min_x_axis: 0,
  max_x_axis: 0,
  y_axis: "Free Axis",
  min_y_axis: 0,
  max_y_axis: 0,
  bandwidth_divisor: 30,
  thresholds: 10,
};

export const DEFAULTS_BY_PLOT: Record<
  Exclude<SummStatFragFilterState["plot"], "">,
  Partial<SummStatFragFilterState>
> = {
  Histogram: {
    var_1: "Length",
    col: ["Ancestry"],
    fac_x: ["Dataset"],
    fac_y: [],
    mea_med_1: false,
    n_bins: 50,
    x_axis: "Shared Axis",
    min_x_axis: 0,
    max_x_axis: 0,
    y_axis: "Free Axis",
    min_y_axis: 0,
    max_y_axis: 0,
  },
  Violin: {
    var_1: "Length",
    col: ["Ancestry"],
    fac_x: ["Dataset"],
    fac_y: [],
    mea_med_1: true,
    x_axis: "Shared Axis",
    min_x_axis: 0,
    max_x_axis: 0,
    y_axis: "Shared Axis",
    min_y_axis: 0,
    max_y_axis: 0,
    bandwidth_divisor: 30,
  },
  Density: {
    var_1: "Length",
    col: ["Ancestry"],
    fac_x: [],
    fac_y: ["Phase State"],
    mea_med_1: true,
    x_axis: "Shared Axis",
    min_x_axis: 0,
    max_x_axis: 0,
    y_axis: "Free Axis",
    min_y_axis: 0,
    max_y_axis: 0,
    bandwidth_divisor: 10,
  },
  Points: {
    var_2_1: "Length",
    var_2_2: "Mean Post. Prob.",
    col: ["Ancestry"],
    fac_x: ["Dataset"],
    fac_y: [],
    mea_med_x: false,
    mea_med_y: false,
    x_axis: "Shared Axis",
    min_x_axis: 0,
    max_x_axis: 0,
    y_axis: "Shared Axis",
    min_y_axis: 0,
    max_y_axis: 0,
  },
  "2D Density": {
    var_2_1: "Length",
    var_2_2: "Mean Post. Prob.",
    col: [],
    fac_x: [],
    fac_y: [],
    mea_med_x: false,
    mea_med_y: false,
    x_axis: "Shared Axis",
    min_x_axis: 0,
    max_x_axis: 0,
    y_axis: "Shared Axis",
    min_y_axis: 0,
    max_y_axis: 0,
    bandwidth_divisor: 10,
    thresholds: 10,
  },
};
